# Generated by Django 5.0.4 on 2024-04-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_videomodel_created_at_videomodel_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='description',
            field=models.TextField(default='default description'),
        ),
    ]
